### PR TITLE
Tokenizer

### PR DESCRIPTION
**Pull request by petrbel**

### CODE REVIEW

**Comment by pasky** [comment]
Hi! Do you have some examples of how the phrases are tokenized? Especialy when the message involves emoticons, shell commands and file paths (backticks...), URLs and other funny stuff.

(In principle, I prefer the idea of using twokenizer that the original dataset used. But maybe my worries are unfounded.)

**Comment by pasky** [comment]
(My tokenization: https://github.com/brmson/dataset-sts/blob/master/data/anssel/ubuntu/preprocess.py and https://github.com/brendano/tweetmotif/compare/master...brmson:master)

**Comment by petrbel** [comment]
Hi! It uses `nltk.word_tokenize` (as we discussed with @rkadlec). AFAIK the URLs are left as they are and emoticons are splitted by chars.

**Comment by petrbel** [comment]
However, one can disable tokenization by omitting `-t` flag and use their own method (or none at all).

**Pull request closed without merging**
